name: CI

on: [push]

jobs:
  php:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.1]
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: composer install --no-interaction --no-progress
    - name: Run tests
      run: php${{ matrix.php }} vendor/bin/phpunit --configuration .phpunit.xml --verbose --fail-on-warning
